[Config]
MinimumVersion=26~devel
Profiles=alchemist,dx,bootc-ostree,fedora-bootc-ostree

[Distribution]
Distribution=alma
Release=10-kitten

[Build]
ToolsTree=default
SandboxTrees=
    global/keys:/etc/pki/rpm-gpg,
    global/repos/almalinux-extras.repo:/etc/yum.repos.d/almalinux-extras.repo
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Validation]
SecureBoot=no
SignExpectedPcr=no

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4

[Output]
ImageId=Alchemist