[Config]
MinimumVersion=26~devel
Profiles=alchemist, bootc

[Distribution]
Distribution=centos
Release=10

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=no

[Validation]
SecureBoot=no
SignExpectedPcr=no

[Runtime]
RuntimeSize=60G
RAM=4G
CPUs=4

[Output]
ImageId=Alchemist