# This is meant to be a viable non-graphical base similar to quay.io/fedora/fedora-bootc:latest with decent-ish hardware support.

[Match]
Distribution=centos

[Distribution]
Distribution=centos
Architecture=x86-64
Release=10

[Build]
SandboxTrees=
    mkosi.global-repos/tailscale.repo:/etc/yum.repos.d/tailscale.repo,
    mkosi.global-repos/ublue.repo:/etc/yum.repos.d/ublue.repo

[Content]
Splash=/usr/share/pixmaps/fedora-logo.png
WithRecommends=true
VolatilePackages=
    systemd
    systemd-boot
    systemd-container
    systemd-oomd-defaults
    systemd-resolved
    udev
    shim-x64
    shim-unsigned-x64
Packages=
    open-vm-tools
    vim
    sudo
    epel-release
    distribution-gpg-keys
    ntfs-3g
    xfsprogs
    btrfs-progs
    lvm2
    plymouth
    plymouth-system-theme
    firewalld
    git
    make
    distrobox
    binutils
    tailscale
    curl
    gcc
    wget
    tmux
    podman
    unzip
    wireguard-tools
    systemd-timesyncd
    rsync
    bash
    linux-firmware
    kernel
    kernel-devel
    kernel-headers
    kernel-modules
    uupd
    zram-generator
    grub2
    grub2-common
    grub2-efi-x64
