[Distribution]
Repositories=epel
Distribution=centos

[Build]
SandboxTrees=
    mkosi.conf.d/repos/negativo.repo:/etc/yum.repos.d/negativo.repo

[Content]
Packages=
    ffmpeg
    libavcodec
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-bad-free-libs
    gstreamer1-plugins-good
    gstreamer1-plugins-base
    lame
    lame-libs
    libjxl
    ffmpegthumbnailer