# Desktop stuff
[Match]
Distribution=centos

[Distribution]
Repositories=epel

[Content]
Splash=/usr/share/pixmaps/fedora-logo.png
WithRecommends=true
# Mainly taken from zirconium-mkosi
Packages=
    qemu-kvm-device-display-virtio-gpu
    spice-vdagent
    mesa-dri-drivers
    centos-backgrounds
    centos-logos
    adobe-source-code-pro-fonts
    adwaita-mono-fonts
    adwaita-sans-fonts
    audispd-plugins
    cups
    cups-browsed
    cups-ipptool
    cups-pk-helper
    ddcutil
    default-fonts
    default-fonts-core-emoji
    dymo-cups-drivers
    flatpak
    ptyxis
    fpaste
    fprintd
    gi-docgen-fonts
    gnome-disk-utility
    gnome-keyring
    gnome-keyring-pam
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    gvfs-fuse
    gvfs-mtp
    gvfs-smb
    hplip
    ifuse
    just
    libcamera
    libcamera-gstreamer
    libcamera-ipa
    libcamera-tools
    libcamera-v4l2
    liberation-mono-fonts
    nautilus
    nautilus-python
    openssh-askpass
    orca
    pipewire
    pipewire-alsa
    pipewire-gstreamer
    pipewire-jack-audio-connection-kit
    pipewire-plugin-libcamera
    pipewire-pulseaudio
    pipewire-utils
    printer-driver-brlaser
    redhat-display-fonts
    redhat-text-fonts
    sane-backends
    sane-backends-drivers-cameras
    sane-backends-drivers-scanners
    usbmuxd
    uxplay
    webp-pixbuf-loader
    wireplumber
    wl-clipboard
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    xdg-terminal-exec
    xdg-user-dirs
    xdg-utils
    xorg-x11-server-Xwayland
    tuned-ppd