[Match]
Distribution=alma

[Content]
Packages=
    grub2-common
    shim
    shim-x64
    grub2-tools-minimal
    bootupd
VolatilePackages=
    grub2-common
    shim
    shim-x64
    grub2-tools-minimal
    bootupd
